services:

  postgresql:
    image: postgres:17
    container_name: postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - pg_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432

  pgadmin:
    build:
      context: .
      dockerfile: Dockerfile.pgadmin
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - ./conf/pgadmin_pass:/pgadmin4/pass
      - ./conf/pgadmin_servers.json:/pgadmin4/servers.json
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - 8080:80
    depends_on: 
      - postgresql

  pubs-txt:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: pubs-txt
    volumes:
      - ./apps/pubs_txt:/app
    environment:
      DB_HOST: postgresql
      DB_PORT: 5432
      DB_NAME: pubs_txt_db
      DB_USER: postgres
      DB_PASSWORD: postgres123
    depends_on: 
      - postgresql

  pubs-json:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: pubs-json
    volumes:
      - ./apps/pubs_json:/app
    environment:
      DB_HOST: postgresql
      DB_PORT: 5432
      DB_NAME: pubs_json_db
      DB_USER: postgres
      DB_PASSWORD: postgres123
    depends_on:
      - postgresql

  flask_app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: always

volumes:
  pg_data:
  pgadmin_data:

